### ISSUE TITLE
PIG script not running? 

### ISSUE THREAD

**Issue by BlancKami** [abajwa-hw/hdp-datascience-demo#1]
Hello, 

I followed the direction for the pig script and try to run it in ipython but it didn't output anything? 

When I used 

%%bash --err pig_out --bg 
pig -f preprocess1.pig

It did say that a job was starting in a separate thread but when I used 

while True:
   ....:         line = pig_out.readline()
   ....:         if not line: 
   ....:                 break
   ....:         sys.stdout.write("%s" % line)
   ....:         sys.stdout.flush()

I did not output anything and just get to a new In [] line? Is my script running at all? 

Thanks for your help! I really need the feature matrices for my model.

**Comment by abajwa-hw** [comment]
Can you check the YARN Resource Manager UI to see if the Pig job was started?

On Apr 17, 2016, at 5:06 PM, BlancKami <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,

I followed the direction for the pig script and try to run it in ipython but it didn't output anything?

When I used

%%bash --err pig_out --bg
pig -f preprocess1.pig

It did say that a job was starting in a separate thread but when I used

while True:
....: line = pig_out.readline()
....: if not line:
....: break
....: sys.stdout.write("%s" % line)
....: sys.stdout.flush()

I did not output anything and just get to a new In [] line? Is my script running at all?

Thanks for your help! I really need the feature matrices for my model.

##

**Comment by BlancKami** [comment]
There is no application showing at all? Screenshot below. The same thing with running and finished tab

![screenshot 2016-04-17 21 37 50](https://cloud.githubusercontent.com/assets/16508059/14591778/f6d96c06-04e4-11e6-9f0f-3a129b8a443d.png)

**Comment by BlancKami** [comment]
This is my terminal and every step I took up until I call read_cvs_from_hdfs() 


`Last login: Sun Apr 17 18:13:32 on ttys005
(master) ~ $ ipython
Python 2.7.11 (default, Apr 17 2016, 00:02:11) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import warnings

In [2]: warnings.filterwarnings('ignore')

In [3]: 

In [3]: import sys

In [4]: import random

In [5]: import numpy as np

In [6]: 

In [6]: from sklearn import linear_model, cross_validation, metrics, svm

In [7]: from sklearn.metrics import confusion_matrix, precision_recall_fscore_support, accuracy_score

In [8]: from sklearn.ensemble import RandomForestClassifier

In [9]: from sklearn.preprocessing import StandardScaler

In [10]: 

In [10]: import pandas as pd

In [11]: import matplotlib.pyplot as plt

In [12]: import pydoop.hdfs as hdfs

In [13]: def read_csv_from_hdfs(path, cols, col_types=None):
   ....:       files = hdfs.ls(path);
   ....:       pieces = []
   ....:       for f in files:
   ....:             fhandle = hdfs.open(f)
   ....:             pieces.append(pd.read_csv(fhandle, names=cols, dtype=col_types))
   ....:             fhandle.close()
   ....:       return pd.concat(pieces, ignore_index=True)
   ....:   

In [14]: cols = ['year', 'month', 'day', 'dow', 'DepTime', 'CRSDepTime', 'ArrTime', 'CRSArrTime', 'Carrier', 'FlightNum', 
   ....:         'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay', 'DepDelay', 'Origin', 'Dest', 
   ....:         'Distance', 'TaxiIn', 'TaxiOut', 'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay', 
   ....:         'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'];

In [15]: flt_2007 = read_csv_from_hdfs('airline/delay/2007.csv', cols)
2016-04-17 21:54:34,688 WARN  [main] util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(62)) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-15-325976df31af> in <module>()
----> 1 flt_2007 = read_csv_from_hdfs('airline/delay/2007.csv', cols)

<ipython-input-13-6bdfe5daa19c> in read_csv_from_hdfs(path, cols, col_types)
      1 def read_csv_from_hdfs(path, cols, col_types=None):
----> 2       files = hdfs.ls(path);
      3       pieces = []
      4       for f in files:
      5             fhandle = hdfs.open(f)

/usr/local/lib/python2.7/site-packages/pydoop/hdfs/__init__.pyc in ls(hdfs_path, user, recursive)
    310     items are hdfs paths instead of dictionaries of properties.
    311     """
--> 312     dir_list = lsl(hdfs_path, user, recursive)
    313     return [d["name"] for d in dir_list]
    314 

/usr/local/lib/python2.7/site-packages/pydoop/hdfs/__init__.pyc in lsl(hdfs_path, user, recursive)
    291     fs = hdfs(host, port, user)
    292     if not recursive:
--> 293         dir_list = fs.list_directory(path_)
    294     else:
    295         treewalk = fs.walk(path_)

/usr/local/lib/python2.7/site-packages/pydoop/hdfs/fs.pyc in list_directory(self, path)
    409         """
    410         _complain_ifclosed(self.closed)
--> 411         return self.fs.list_directory(path)
    412 
    413     def move(self, from_path, to_hdfs, to_path):

IOError: [Errno 2] No such file or directory

In [16]: 
`

**Comment by BlancKami** [comment]
I was able to get the script to run in grunt shell. However, the output is a folder with lots of text file in stead of 1 csv file (I'm only processed 2007.csv). While the script was running, my YARN Resource Manager did not show any activity of any application either?? 

The folder: 

![screenshot 2016-04-18 17 45 31](https://cloud.githubusercontent.com/assets/16508059/14620913/781d1d3c-058d-11e6-8c7b-40fb4adac5b3.png)

A snipet of a file: 

```
-8,1,25,4,11,719,XE,EWR,10
41,1,28,7,15,925,XE,IAH,13
45,1,29,1,20,316,XE,CLE,14
-9,1,17,3,19,719,XE,EWR,2
```

I have attached my terminal output from running the script follows pig -x local. Is it a type conversion failure and how to fix it? 

[Terminal Saved Output 2.zip](https://github.com/abajwa-hw/hdp-datascience-demo/files/224836/Terminal.Saved.Output.2.zip)

**Comment by abajwa-hw** [comment]
Ok looks like it ran successfully. Seems like its running Pig in local mode so the job doesn’t show up on YARN.
I think you should be able to proceed with the remaining steps

On Apr 18, 2016, at 2:46 PM, BlancKami <notifications@github.com<mailto:notifications@github.com>> wrote:

I was able to get the script to run in grunt shell. However, the output is a folder with lots of text file in stead of 1 csv file (I'm only processed 2007.csv). While the script was running, my YARN Resource Manager did not show any activity of any application either??

The folder:

[screenshot 2016-04-18 17 45 31]https://cloud.githubusercontent.com/assets/16508059/14620913/781d1d3c-058d-11e6-8c7b-40fb4adac5b3.png

A snipet of a file:

-8,1,25,4,11,719,XE,EWR,10
41,1,28,7,15,925,XE,IAH,13
45,1,29,1,20,316,XE,CLE,14
-9,1,17,3,19,719,XE,EWR,2

I have attached my terminal output from running the script follows pig -x local.

Terminal Saved Output 2.ziphttps://github.com/abajwa-hw/hdp-datascience-demo/files/224836/Terminal.Saved.Output.2.zip
